name: release
run-name: Build a release
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          clojure -T:build jar
          clojure -T:build deploy
